START TRANSACTION;

UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'accessnumber' AND `module_url` = 'accessnumber_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'accounts' AND `module_url` = 'admin_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'customers' WHERE `module_name` = 'accounts' AND `module_url` = 'customer_list' AND `sub_module_name` <> 'customers';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'accounts' AND `module_url` = 'reseller_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'activity_report' AND `module_url` = 'activityReport' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'customers' WHERE `module_name` = 'animap' AND `module_url` = 'animap_detail' AND `sub_module_name` <> 'customers';
UPDATE `roles_and_permission` SET `sub_module_name` = 'api' WHERE `module_name` = 'api_endpoints' AND `module_url` = 'api_endpoints_list' AND `sub_module_name` <> 'api';
UPDATE `roles_and_permission` SET `sub_module_name` = 'api' WHERE `module_name` = 'api_endpoints' AND `module_url` = 'partners_endpoints_list' AND `sub_module_name` <> 'api';
UPDATE `roles_and_permission` SET `sub_module_name` = 'api' WHERE `module_name` = 'api_endpoints' AND `module_url` = 'partners_list' AND `sub_module_name` <> 'api';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'audit' AND `module_url` = 'audit_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'automated_report' AND `module_url` = 'automated_report_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'calltype' AND `module_url` = 'calltype_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'cronsettings' AND `module_url` = 'cronsettings_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'call_detail_reports' WHERE `module_name` = 'detraf_reports' AND `module_url` = 'detraf_reports_list' AND `sub_module_name` <> 'call_detail_reports';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'did' AND `module_url` = 'did_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'email' AND `module_url` = 'email_history_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'event_guard' WHERE `module_name` = 'event_guard' AND `module_url` = 'event_guard_list' AND `sub_module_name` <> 'event_guard';
UPDATE `roles_and_permission` SET `sub_module_name` = 'event_guard' WHERE `module_name` = 'event_guard' AND `module_url` = 'event_guard_whitelist_list' AND `sub_module_name` <> 'event_guard';
UPDATE `roles_and_permission` SET `sub_module_name` = 'customers' WHERE `module_name` = 'flux_import' AND `module_url` = 'flux_import_list' AND `sub_module_name` <> 'customers';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'freeswitch' AND `module_url` = 'fsgateway' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'customers' WHERE `module_name` = 'freeswitch' AND `module_url` = 'fssipdevices' AND `sub_module_name` <> 'customers';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'freeswitch' AND `module_url` = 'fssipprofile' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'freeswitch' AND `module_url` = 'livecall_report' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'fsjsoncdr' AND `module_url` = 'cdr_mode' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'fsmonitor' AND `module_url` = 'fs_cli' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'invoices' AND `module_url` = 'invoice_conf_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'invoices' AND `module_url` = 'invoice_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'customers' WHERE `module_name` = 'ipmap' AND `module_url` = 'ipmap_detail' AND `sub_module_name` <> 'customers';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'local_number' AND `module_url` = 'local_number_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'local_number' AND `module_url` = 'local_number_list_customer' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'localization' AND `module_url` = 'localization_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'low_balance' AND `module_url` = 'low_balance_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'opensips' AND `module_url` = 'opensips_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'orders' AND `module_url` = 'orders_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'permissions' AND `module_url` = 'permissions_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'personalized_rates' AND `module_url` = 'personalized_rates_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'pricing' AND `module_url` = 'price_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'pricing' AND `module_url` = 'price_refactor' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'products' AND `module_url` = 'products_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'products' AND `module_url` = 'products_topuplist' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'ratedeck' AND `module_url` = 'ratedeck_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'rates' AND `module_url` = 'origination_rates_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'rates' AND `module_url` = 'resellersrates_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'rates' AND `module_url` = 'termination_rates_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'refill_coupon' AND `module_url` = 'refill_coupon_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'reports' AND `module_url` = 'commission_report_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'call_detail_reports' WHERE `module_name` = 'reports' AND `module_url` = 'customerReport' AND `sub_module_name` <> 'call_detail_reports';
UPDATE `roles_and_permission` SET `sub_module_name` = 'call_detail_reports' WHERE `module_name` = 'reports' AND `module_url` = 'providerReport' AND `sub_module_name` <> 'call_detail_reports';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'reports' AND `module_url` = 'refillreport' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'call_detail_reports' WHERE `module_name` = 'reports' AND `module_url` = 'resellerReport' AND `sub_module_name` <> 'call_detail_reports';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'ringgroup' AND `module_url` = 'ringgroup_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'sngrep_captures' AND `module_url` = 'sngrep_captures_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'call_summary_reports' WHERE `module_name` = 'summary' AND `module_url` = 'customer' AND `sub_module_name` <> 'call_summary_reports';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'summary' AND `module_url` = 'product' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'call_summary_reports' WHERE `module_name` = 'summary' AND `module_url` = 'provider' AND `sub_module_name` <> 'call_summary_reports';
UPDATE `roles_and_permission` SET `sub_module_name` = 'call_summary_reports' WHERE `module_name` = 'summary' AND `module_url` = 'reseller' AND `sub_module_name` <> 'call_summary_reports';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'systems' AND `module_url` = 'configuration' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'systems' AND `module_url` = 'country_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'systems' AND `module_url` = 'currency_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'systems' AND `module_url` = 'database_restore' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'languages' WHERE `module_name` = 'systems' AND `module_url` = 'languages_list' AND `sub_module_name` <> 'languages';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'systems' AND `module_url` = 'template' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'systems' AND `module_url` = 'timezone_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = 'languages' WHERE `module_name` = 'systems' AND `module_url` = 'translation_list' AND `sub_module_name` <> 'languages';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'systems' AND `module_url` = 'update' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'taxes' AND `module_url` = 'taxes_list' AND `sub_module_name` <> '';
UPDATE `roles_and_permission` SET `sub_module_name` = '' WHERE `module_name` = 'trunk' AND `module_url` = 'trunk_list' AND `sub_module_name` <> '';

INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'api_endpoints', 'api', 'api_endpoints_list', 'API Endpoints', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.03000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'api_endpoints', 'api', 'partners_endpoints_list', 'Partners Endpoints', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'api_endpoints', 'api', 'partners_list', 'API Partners', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.04000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'reports', 'automated_report', '', 'automated_report_list', 'Automated Reports', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 8.97000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'cronsettings', '', 'cronsettings_list', 'Crons', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.08000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'reports', 'detraf_reports', 'call_detail_reports', 'detraf_reports_list', 'Detraf Reports', '[\"main\",\"list\",\"search\",\"create\",\"edit\",\"delete\"]', 0, '2026-08-06 00:00:00', 8.02000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'switch', 'fsmonitor', '', 'fs_cli', 'FluxSBC CLI', '[\"main\",\"list\"]', 0, '2026-08-06 00:00:00', 7.06000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'inbound', 'local_number', '', 'local_number_list_customer', 'Local Numbers', '[\"main\",\"list\",\"search\",\"create\",\"export\",\"import\",\"delete\"]', 0, '2026-08-06 00:00:00', 3.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'switch', 'opensips', '', 'opensips_list', 'Opensips devices', '[\"main\",\"list\",\"search\"]', 0, '2026-08-06 00:00:00', 9.02000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'tariff', 'ratedeck', '', 'ratedeck_list', 'Ratedeck', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 4.03000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'reports', 'summary', 'call_summary_reports', 'provider', 'Provider', '[\"main\",\"list\",\"search\",\"export\"]', 0, '2026-08-06 00:00:00', 8.13000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'systems', '', 'configuration', 'Settings', '[\"main\",\"list\",\"edit\"]', 0, '2026-08-06 00:00:00', 9.09000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'systems', '', 'country_list', 'Countries', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.04000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'systems', '', 'currency_list', 'Currencies', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'systems', '', 'database_restore', 'Database Backup', '[\"main\",\"list\"]', 0, '2026-08-06 00:00:00', 9.06000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'systems', 'languages', 'languages_list', 'Languages', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.11000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'systems', '', 'timezone_list', 'Timezone', '[\"main\",\"list\",\"search\"]', 0, '2026-08-06 00:00:00', 9.07000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'systems', 'languages', 'translation_list', 'Translations', '[\"main\",\"list\",\"edit\",\"search\"]', 0, '2026-08-06 00:00:00', 9.12000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (1, 0, 'configuration', 'systems', '', 'update', 'Updates', '[\"main\",\"list\"]', 0, '2026-08-06 00:00:00', 9.03000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'configuration', 'api_endpoints', 'api', 'api_endpoints_list', 'API Endpoints', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.03000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'configuration', 'api_endpoints', 'api', 'partners_endpoints_list', 'Partners Endpoints', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'configuration', 'api_endpoints', 'api', 'partners_list', 'API Partners', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.04000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'reports', 'automated_report', '', 'automated_report_list', 'Automated Reports', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 8.97000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'reports', 'detraf_reports', 'call_detail_reports', 'detraf_reports_list', 'Detraf Reports', '[\"main\",\"list\",\"search\",\"create\",\"edit\",\"delete\"]', 0, '2026-08-06 00:00:00', 8.02000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'switch', 'fsmonitor', '', 'fs_cli', 'FluxSBC CLI', '[\"main\",\"list\"]', 0, '2026-08-06 00:00:00', 7.06000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'inbound', 'local_number', '', 'local_number_list', 'Local Numbers', '[\"main\",\"list\",\"search\",\"create\",\"export\",\"import\",\"delete\"]', 0, '2026-08-06 00:00:00', 3.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'inbound', 'local_number', '', 'local_number_list_customer', 'Local Numbers', '[\"main\",\"list\",\"search\",\"create\",\"export\",\"import\",\"delete\"]', 0, '2026-08-06 00:00:00', 3.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'switch', 'opensips', '', 'opensips_list', 'Opensips devices', '[\"main\",\"list\",\"search\"]', 0, '2026-08-06 00:00:00', 9.02000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'tariff', 'personalized_rates', '', 'personalized_rates_list', 'Personalized Rates', '[\"main\",\"list\",\"search\",\"create\",\"edit\",\"delete\",\"export\"]', 0, '2026-08-06 00:00:00', 4.08000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'tariff', 'ratedeck', '', 'ratedeck_list', 'Ratedeck', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 4.03000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'reports', 'summary', 'call_summary_reports', 'provider', 'Provider', '[\"main\",\"list\",\"search\",\"export\"]', 0, '2026-08-06 00:00:00', 8.13000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'configuration', 'systems', '', 'configuration', 'Settings', '[\"main\",\"list\",\"edit\"]', 0, '2026-08-06 00:00:00', 9.09000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'configuration', 'systems', '', 'country_list', 'Countries', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.04000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'configuration', 'systems', '', 'currency_list', 'Currencies', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'configuration', 'systems', '', 'database_restore', 'Database Backup', '[\"main\",\"list\"]', 0, '2026-08-06 00:00:00', 9.06000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'configuration', 'systems', 'languages', 'languages_list', 'Languages', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.11000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'configuration', 'systems', '', 'timezone_list', 'Timezone', '[\"main\",\"list\",\"search\"]', 0, '2026-08-06 00:00:00', 9.07000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'configuration', 'systems', 'languages', 'translation_list', 'Translations', '[\"main\",\"list\",\"edit\",\"search\"]', 0, '2026-08-06 00:00:00', 9.12000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (2, 0, 'configuration', 'systems', '', 'update', 'Updates', '[\"main\",\"list\"]', 0, '2026-08-06 00:00:00', 9.03000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);

INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'configuration', 'api_endpoints', 'api', 'api_endpoints_list', 'API Endpoints', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.03000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'configuration', 'api_endpoints', 'api', 'partners_endpoints_list', 'Partners Endpoints', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'configuration', 'api_endpoints', 'api', 'partners_list', 'API Partners', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.04000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'reports', 'automated_report', '', 'automated_report_list', 'Automated Reports', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 8.97000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'configuration', 'cronsettings', '', 'cronsettings_list', 'Crons', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.08000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'reports', 'detraf_reports', 'call_detail_reports', 'detraf_reports_list', 'Detraf Reports', '[\"main\",\"list\",\"search\",\"create\",\"edit\",\"delete\"]', 0, '2026-08-06 00:00:00', 8.02000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'accounts', 'flux_import', 'customers', 'flux_import_list', 'Import Customers', '[\"main\",\"list\",\"create\",\"export\",\"import\",\"delete\",\"edit\"]', 0, '2026-08-06 00:00:00', 1.08000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'switch', 'fsmonitor', '', 'fs_cli', 'FluxSBC CLI', '[\"main\",\"list\"]', 0, '2026-08-06 00:00:00', 7.06000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'inbound', 'local_number', '', 'local_number_list', 'Local Numbers', '[\"main\",\"list\",\"search\",\"create\",\"export\",\"import\",\"delete\"]', 0, '2026-08-06 00:00:00', 3.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'inbound', 'local_number', '', 'local_number_list_customer', 'Local Numbers', '[\"main\",\"list\",\"search\",\"create\",\"export\",\"import\",\"delete\"]', 0, '2026-08-06 00:00:00', 3.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'switch', 'opensips', '', 'opensips_list', 'Opensips devices', '[\"main\",\"list\",\"search\"]', 0, '2026-08-06 00:00:00', 9.02000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'tariff', 'personalized_rates', '', 'personalized_rates_list', 'Personalized Rates', '[\"main\",\"list\",\"search\",\"create\",\"edit\",\"delete\",\"export\"]', 0, '2026-08-06 00:00:00', 4.08000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'tariff', 'ratedeck', '', 'ratedeck_list', 'Ratedeck', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 4.03000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (3, 0, 'reports', 'summary', 'call_summary_reports', 'provider', 'Provider', '[\"main\",\"list\",\"search\",\"export\"]', 0, '2026-08-06 00:00:00', 8.13000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);

INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'configuration', 'api_endpoints', 'api', 'api_endpoints_list', 'API Endpoints', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.03000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'configuration', 'api_endpoints', 'api', 'partners_endpoints_list', 'Partners Endpoints', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'configuration', 'api_endpoints', 'api', 'partners_list', 'API Partners', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.04000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'reports', 'audit', '', 'audit_list', 'Audit Log', '[\"main\",\"list\"]', 0, '2026-08-06 00:00:00', 8.22000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'reports', 'automated_report', '', 'automated_report_list', 'Automated Reports', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 8.97000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'tariff', 'calltype', '', 'calltype_list', 'Call Types', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 5.50000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'configuration', 'cronsettings', '', 'cronsettings_list', 'Crons', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 9.08000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'reports', 'email', '', 'email_history_list', 'Email History', '[\"main\",\"list\"]', 0, '2026-08-06 00:00:00', 8.21000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'switch', 'freeswitch', '', 'fssipprofile', 'SIP Profiles', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 7.01000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'switch', 'fsjsoncdr', '', 'cdr_mode', 'CDR Mode', '[\"main\",\"list\"]', 0, '2026-08-06 00:00:00', 7.02000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'switch', 'fsmonitor', '', 'fs_cli', 'FluxSBC CLI', '[\"main\",\"list\"]', 0, '2026-08-06 00:00:00', 7.06000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'inbound', 'local_number', '', 'local_number_list_customer', 'Local Numbers', '[\"main\",\"list\",\"search\",\"create\",\"export\",\"import\",\"delete\"]', 0, '2026-08-06 00:00:00', 3.05000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'switch', 'opensips', '', 'opensips_list', 'Opensips devices', '[\"main\",\"list\",\"search\"]', 0, '2026-08-06 00:00:00', 9.02000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);
INSERT INTO `roles_and_permission` (`login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES (0, 0, 'tariff', 'ratedeck', '', 'ratedeck_list', 'Ratedeck', '[\"main\",\"list\",\"create\",\"edit\",\"delete\",\"search\"]', 0, '2026-08-06 00:00:00', 4.03000)
  ON DUPLICATE KEY UPDATE `display_name` = VALUES(`display_name`), `permissions` = VALUES(`permissions`), `status` = VALUES(`status`), `priority` = VALUES(`priority`);

COMMIT;
